In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

In [2]:
np.random.seed(33550336)

In [3]:
x = np.array([[0, 0], [1, 1]])
y = np.array([-1, 1])
k = x @ x.T

In [4]:
k

array([[0, 0],
       [0, 2]])

In [7]:
bnd = [(0, None), (0, None)]

In [11]:
def eq(alph):
    return np.sum(alph * y)

In [15]:
def som(alph):
    t1 = np.sum(alph)
    sm = 0
    for i in range(2):
        for j in range(2):
            sm += alph[i] * alph[j] * y[i] * y[j] * k[i, j]
    t2 = sm * 0.5
    return -(t1 - t2)

In [12]:
sm = {'type' : 'eq', 'fun' : eq}

In [13]:
sm

{'type': 'eq', 'fun': <function __main__.eq(alph)>}

In [16]:
res = sp.optimize.minimize(som, x0=[0.1, 0.1], method='SLSQP', bounds=bnd, constraints=sm)

In [18]:
alpha = res.x

In [19]:
w = np.sum(alpha[:, None] * y[:, None] * x, axis = 0)

In [21]:
b = y[1] - np.dot(w, x[1])

In [22]:
alpha

array([0.99999999, 0.99999999])

In [23]:
w

array([0.99999999, 0.99999999])

In [24]:
b

np.float64(-0.999999985843897)