In [1]:
import numpy as np

In [4]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [6]:
#All 1s matrix
np.ones((4, 2, 2), dtype = 'int8')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [8]:
#Any other number (full)
np.full((2,2) , 99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [10]:
#Any other number (full_like)
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [13]:
# Matrix of random decimal numbers (random_sample if we want to pass in a shape)
np.random.rand(4, 2, 3)
np.random.random_sample(a.shape)

array([[0.17336621, 0.78984801, 0.67281712, 0.66448152, 0.83034742,
        0.13117196, 0.68677721],
       [0.55425533, 0.73819422, 0.92960716, 0.62766149, 0.68043094,
        0.43075052, 0.65021055]])

In [18]:
# Random integer values, inclusive for start, exclusive for end (automatically intiialized to 0 for start, max needs to be given)
np.random.randint(3, size = (3,3))

array([[1, 2, 1],
       [0, 2, 2],
       [1, 2, 2]], dtype=int32)

In [19]:
#Idnetity matrix (n by n)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
#Repeat an array
arr = np.array([[1,2,3], [4,5,6]])
r1 = np.repeat(arr, 3, axis = 1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

In [33]:
#picture challenge
output = np.ones((5, 5))
output[1:4, 1:4] = [0, 0, 0]
output[2,2] = 9
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 4
b

array([4, 2, 3])

In [1]:
import scipy
print(scipy.__version__)


1.18.0
