In [1]:
import numpy as np

In [ ]:
fdata = np.genfromtxt('data.txt', delimeter = ',') 
fdata.astype('int32')
fdata = fdata.astype('inte32')

In [ ]:
fdata > 50

In [ ]:
fdata[fdata > 50]

In [3]:
##You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1, 2, 8]]

array([2, 3, 9])

In [44]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20],[21,22,23,24,25], [26, 27, 28, 29, 30]])
print(a[2 : 4, 0 : 2])
print(a[(a % 6 == 2) & (a < 25)])
print(a[[0, 4, 5], 3:])

[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
