In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3, 4])
b = np.array([5, 6, 7, 8])

In [4]:
a + 2

array([3, 4, 5, 6])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [6]:
a * 2

array([2, 4, 6, 8])

In [7]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [8]:
a+b

array([ 6,  8, 10, 12])

In [9]:
a * b

array([ 5, 12, 21, 32])

In [11]:
a ** 2

array([ 1,  4,  9, 16])

In [15]:
# Take the sine
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [22]:
a = np.ones((2, 3))
print(a)
b = np.full((3,2), 2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [25]:
#Determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [27]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.min(stats)

np.int64(1)

In [29]:
np.max(stats)

np.int64(6)

In [30]:
np.min(stats, axis = 1)

array([1, 4])

In [31]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [34]:
 np.sum(stats, axis = 1)

array([ 6, 15])