In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [6]:
#Get a specific eleemnt, we use row column, so [r, c]
a[1, -2]

np.int64(13)

In [8]:
#Get a specific row
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
#get a column
a[:,2]

array([ 3, 10])

In [14]:
# Getting a little more fancy [startindex: endindex:steps]
a[0, 1:-1:2]

array([2, 4, 6])

In [17]:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [21]:
a[:, 2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [22]:
a[:, 2] = [3, 4]
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9,  4, 11, 12, 20, 14]])

In [23]:
#3d example
b = np.array([[[1, 2], [3,4]], [[5, 6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
#Get specific element(work outside in)
b[:, 0, 0]

array([1, 5])

In [32]:
#replace element (same idea, subsequence of same dimension)
b[:, 1, :] = [[9, 9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])