In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

In [7]:
W = np.array([[1.0, 2.0],
              [3.0, 4.0],
              [5.0, 6.0]])
x = np.array([1.0, 2.0])
b = np.array([1.0, 1.0, 1.0])
dldy = np.array([1.0, 2.0, 3.0])

In [8]:
def fowardpass(x, W, b):
    return W @ x + b

In [10]:
def backwardpass(dldy, x, W):
    dldw = np.outer(dldy, x)
    dldx = W.T @ dldy
    dldb = dldy
    return dldw, dldx, dldb

dw, dx, db = backwardpass(dldy, x, W)
print(dw)
print(dx)
print(db)

[[1. 2.]
 [2. 4.]
 [3. 6.]]
[22. 28.]
[1. 2. 3.]


In [11]:
z = np.array([1.0, 2.0, 0.5])
y = np.array([0, 1, 0])

In [12]:
def softmax(z):
    zshift = z - np.max(z)
    expz = np.exp(zshift)
    sig = expz/np.sum(expz)
    return sig

In [14]:
pt = softmax(z)

In [15]:
dldz = pt - y

In [22]:
dldz

array([ 0.2312239 , -0.37146828,  0.14024438])

In [20]:
def ce(z, y):
    pt = softmax(z)
    pt = np.clip(pt, 1e-7, 1e7)
    return -np.sum(y * np.log(pt))

In [21]:
def cel(z, y, h):
    for i in range(3):
        zp = z.copy()
        zm = z.copy()
        zp[i] += h
        zm[i] -= h
        sm = ((ce(zp, y) - ce(zm, y))/(2 * h))
        print(sm)

cel(z, y, 1e-6)

0.23122389755658723
-0.3714682807742786
0.14024438316218024
