In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

In [2]:
def vv(x):
    return np.array([x[0] ** 2, x[0] * x[1], x[1] ** 2])

In [9]:
def jacob(f, x, h):
    xp = x.copy()
    xm = x.copy()
    resa = []
    for i in range(2):
        xp[i] += h
        xm[i] -= h
        fp = vv(xp)
        fm = vv(xm)
        resa.append((fp - fm)/(2 * h))
        xp[i] -= h
        xm[i] += h
    return np.array(resa).T
    
x = np.array([1.0, 2.0])
jacob(vv, x, 1e-6)

array([[ 2.00000000e+00, -1.11022302e-10],
       [ 2.00000000e+00,  1.00000000e+00],
       [ 0.00000000e+00,  4.00000000e+00]])

In [11]:
def softmax(z):
    zshift = z - np.max(z)
    expz = np.exp(zshift)
    sig = expz/np.sum(expz)
    return sig

z = np.array([1.0, 2.0, 0.5])
np.sum(softmax(z))

np.float64(1.0)

In [12]:
def smjacob(z):
    sig = softmax(z)
    j = np.diag(sig) - np.outer(sig, sig)
    return j

smjacob(z)

array([[ 0.17775941, -0.14533155, -0.03242785],
       [-0.14533155,  0.2334796 , -0.08814804],
       [-0.03242785, -0.08814804,  0.1205759 ]])

In [14]:
nj = jacob(softmax, np.array([1.0, 2.0, 0.5]), 1e-6)
nj

array([[ 2.00000000e+00, -1.11022302e-10],
       [ 2.00000000e+00,  1.00000000e+00],
       [ 0.00000000e+00,  4.00000000e+00]])