In [3]:
import numpy as np
import matplotlib as plt
import scipy as sp

In [4]:
from scipy.optimize import minimize

In [10]:
def f(x):
    return 5 * x ** 3 - 10 * x ** 2 + 3 * x - 5

In [12]:
def df(x, h = 1e-5):
    return (f(x+h) - f(x-h))/(2 * h)
df(1.0)

-1.999999999569013

In [13]:
from scipy.optimize import fsolve

In [17]:
root1 = fsolve(df, x0 = 0)
root1

array([0.17225343])

In [18]:
root2 = fsolve(df, x0 = 2)
root2

array([1.1610799])

In [19]:
def d2f(x, h = 1e-5):
    return(df(x+h) - df(x-h))/(2*h)

d2f(root1)

array([-14.83239753])

In [20]:
d2f(root2)

array([14.83239531])

In [21]:
from scipy.integrate import quad

In [23]:
def f(x):
    return x ** 2

In [29]:
def trapezodial(f, a, b, n):
    x = np.linspace(a,b, n + 1)
    y = f(x)
    h = (a + b)/n
    coeffs = np.ones_like(y)
    coeffs[1 : -1] = 2
    return (h / 2) * np.sum(y * coeffs)

res = trapezodial(f, 0, 1, 1000000)
res

np.float64(0.33333333333349996)

In [30]:
def simpson(f, a, b, n):
    if n % 2 == 1:
        return
    x = np.linspace(a, b, n + 1)
    y = f(x)
    h = (b - a) / n
    coeffs = np.ones_like(y)
    coeffs[1 : -1 : 2] = 4
    coeffs[2 : -1 : 2] = 2
    return (h / 3) * np.sum(y * coeffs)

res = simpson(f, 0, 1, 4)
res

np.float64(0.3333333333333333)

In [39]:
def integrand(x):
    return x * (1/np.sqrt(2 * np.pi)) * np.exp(-x ** 2 / 2)

res = trapezodial(integrand, -5, 5, 1000)
res

np.float64(0.0)

In [37]:
a,b  = quad(integrand, -5, 5)
a

0.0