In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

In [2]:
from scipy.linalg import solve_triangular

In [5]:
a = np.array([[3, 0, 0, 0],
             [2, 1, 0, 0],
             [1, 0, 1, 0],
             [1, 1, 1, 1]])
b = np.array([4, 2, 4, 2])
x = solve_triangular(a, b, lower = True)
x

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

In [7]:
from scipy.linalg import solve_toeplitz, toeplitz

In [9]:
c = np.array([1, 3, 6, 10]) #first col
r = np.array([1, -1, -2, -3]) #first row
b = np.array([1, 2, 2, 5]) 
x = solve_toeplitz((c, r), b)
x

array([ 1.66666667, -1.        , -2.66666667,  2.33333333])

In [11]:
from scipy.linalg import eigh_tridiagonal

In [13]:
d = 3 *np.ones(4)
e = -1*np.ones(3)
w,v = eigh_tridiagonal(d,e)

In [16]:
A = np.diag(d) + np.diag(e, k =1) + np.diag(e, k = -1)

In [17]:
A @ v.T[1]

array([-1.43275483, -0.88549118,  0.88549118,  1.43275483])

In [18]:
w[1] * v.T[1]

array([-1.43275483, -0.88549118,  0.88549118,  1.43275483])

In [19]:
from scipy.linalg import fiedler
fiedler([1, 4, 12, 45])

array([[ 0,  3, 11, 44],
       [ 3,  0,  8, 41],
       [11,  8,  0, 33],
       [44, 41, 33,  0]])

In [20]:
from scipy.linalg import toeplitz
toeplitz([1, 2, 3, 6, 0, 0], [1, 4, 5, 6, 0, 0])

array([[1, 4, 5, 6, 0, 0],
       [2, 1, 4, 5, 6, 0],
       [3, 2, 1, 4, 5, 6],
       [6, 3, 2, 1, 4, 5],
       [0, 6, 3, 2, 1, 4],
       [0, 0, 6, 3, 2, 1]])

In [21]:
from scipy.linalg import lu

In [22]:
A = np.array([[2,5,7,8], [5,2,2,8], [7, 5, 6, 6], [5, 4, 4, 8]])

In [23]:
A

array([[2, 5, 7, 8],
       [5, 2, 2, 8],
       [7, 5, 6, 6],
       [5, 4, 4, 8]])

In [24]:
p, l, u = lu(A)

In [25]:
p

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [26]:
l

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.28571429,  1.        ,  0.        ,  0.        ],
       [ 0.71428571,  0.12      ,  1.        ,  0.        ],
       [ 0.71428571, -0.44      , -0.04347826,  1.        ]])

In [27]:
u

array([[ 7.        ,  5.        ,  6.        ,  6.        ],
       [ 0.        ,  3.57142857,  5.28571429,  6.28571429],
       [ 0.        ,  0.        , -0.92      ,  2.96      ],
       [ 0.        ,  0.        ,  0.        ,  6.60869565]])

In [28]:
from scipy.linalg import cholesky

In [29]:
A = np.array([[1,0.2], [0.2, 1]])
A

array([[1. , 0.2],
       [0.2, 1. ]])

In [30]:
C = cholesky(A, lower = True)

In [31]:
C

array([[1.       , 0.       ],
       [0.2      , 0.9797959]])

In [33]:
C.T

array([[1.       , 0.2      ],
       [0.       , 0.9797959]])