In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

In [5]:
np.random.seed(33550336)
rng = np.random.default_rng()

In [8]:
stuff = rng.random((5, 3))

In [23]:
stuff

array([[0.71510683, 0.3531796 , 0.26727777],
       [0.2615036 , 0.30421937, 0.37966339],
       [0.47256754, 0.82721208, 0.69042054],
       [0.31415391, 0.88544425, 0.33065425],
       [0.63098117, 0.59019584, 0.42867252]])

In [11]:
stuff[2, 0] = np.nan
stuff[1, 2] = np.nan
stuff[4, 1] = np.nan

In [12]:
stuff

array([[0.71510683, 0.3531796 , 0.26727777],
       [0.2615036 , 0.30421937,        nan],
       [       nan, 0.82721208, 0.69042054],
       [0.31415391, 0.88544425, 0.33065425],
       [0.63098117,        nan, 0.42867252]])

In [15]:
cm = np.sum(np.isnan(stuff), axis = 0)

In [16]:
cm

array([1, 1, 1])

In [18]:
cm/stuff.shape[0] * 100

array([20., 20., 20.])

In [20]:
meds = np.nanmedian(stuff, axis = 0)

In [21]:
stuff[2, 0] = meds[0]
stuff[1, 2] = meds[2]
stuff[4, 1] = meds[1]

In [22]:
stuff

array([[0.71510683, 0.3531796 , 0.26727777],
       [0.2615036 , 0.30421937, 0.37966339],
       [0.47256754, 0.82721208, 0.69042054],
       [0.31415391, 0.88544425, 0.33065425],
       [0.63098117, 0.59019584, 0.42867252]])

In [25]:
rad = 7
targ = 50
nm = rng.integers(low = targ - rad, high = targ + rad, size = 20, endpoint = True)

In [30]:
rn1 = rng.integers(0, 20)
rn2 = rng.integers(0, 20)

In [35]:
nm[rn1] = -100

In [34]:
nm[rn2] = 500

In [36]:
nm

array([  44,   57,   51,   52,   44,  500,   50,   54,   52,   54,   54,
         49,   44,   44,   57,   47,   55,   48, -100,   49])

In [38]:
q1 = np.percentile(nm, 25)
q3 = np.percentile(nm, 75)

In [42]:
iqr = q3 - q1

In [43]:
lowerb = q1 - 1.5 * iqr
upperb = q3 + 1.5 * iqr

In [44]:
np.clip(nm, lowerb, upperb)

array([44.   , 57.   , 51.   , 52.   , 44.   , 65.625, 50.   , 54.   ,
       52.   , 54.   , 54.   , 49.   , 44.   , 44.   , 57.   , 47.   ,
       55.   , 48.   , 34.625, 49.   ])

In [45]:
sm = np.array(['Low', 'Medium', 'High', 'Medium', 'Low', 'High'])
smnum = np.array([0, 1, 2, 1, 0, 2])

In [46]:
unord = np.array(['Red', 'Green', 'Blue', 'Red'])

In [48]:
sm = np.zeros((4,3))

In [52]:
sm[0, 0] = 1
sm[1, 1] = 1
sm[2, 2] = 1
sm[3, 0] = 1

In [53]:
sm

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [54]:
col1 = rng.integers(low =  20, high = 60, size = 5, endpoint = True)
col2 = rng.integers(low = 20000, high = 150000, size = 5, endpoint = True)

In [55]:
print(col1)
print(col2)

[24 46 51 25 38]
[135734  20278  34799  70751  28868]


In [65]:
newarray = np.column_stack((col1, col2))

In [66]:
newarray

array([[    24, 135734],
       [    46,  20278],
       [    51,  34799],
       [    25,  70751],
       [    38,  28868]])

In [69]:
mins = np.min(newarray, axis = 0)
maxs = np.max(newarray, axis = 0)

In [70]:
tmp = newarray.copy()
xnorm = (tmp - mins)/(maxs- mins)

In [74]:
mu = np.mean(newarray , axis = 0)
sig = np.std(newarray, axis = 0)

In [75]:
Z = (newarray - mu)/sig

In [76]:
Z

array([[-1.17753745,  1.82865413],
       [ 0.84635504, -0.89039969],
       [ 1.30633061, -0.54842196],
       [-1.08554234,  0.29826788],
       [ 0.11039414, -0.68810035]])

In [77]:
son = col1 ** 2

In [78]:
son2 = col1 * col2

In [80]:
son3 = np.column_stack((son, son2))

In [84]:
newthing = np.column_stack((newarray, son3))

In [85]:
newthing

array([[     24,  135734,     576, 3257616],
       [     46,   20278,    2116,  932788],
       [     51,   34799,    2601, 1774749],
       [     25,   70751,     625, 1768775],
       [     38,   28868,    1444, 1096984]])

In [86]:
ind = np.arange(5)
rng.shuffle(ind)

In [87]:
split = 4

In [88]:
tran = ind[:split]
tast = ind[split:]

In [89]:
xtr = newthing[tran]
xte = newthing[tast]

In [90]:
xtr

array([[     51,   34799,    2601, 1774749],
       [     24,  135734,     576, 3257616],
       [     46,   20278,    2116,  932788],
       [     38,   28868,    1444, 1096984]])

In [91]:
xte

array([[     25,   70751,     625, 1768775]])