In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

In [30]:
np.random.seed(33550336)
rng = np.random.default_rng()

In [6]:
n = 25
dat = np.random.normal(loc = 5.5, scale = 2, size = 25)

In [7]:
mu0 = 5.0
alpha = 0.05

In [8]:
xhat = np.mean(dat)
sstd = np.std(dat,ddof = 1)

In [9]:
se = sstd/5

In [10]:
tstat = (xhat - mu0)/se

In [11]:
sm = sp.stats.t.cdf(np.abs(tstat), df = 24)

In [12]:
halfpv = 1.0 - sm

In [13]:
2 * halfpv

np.float64(0.39075175029508036)

In [14]:
sp.stats.ttest_1samp(dat, 5.0)

TtestResult(statistic=np.float64(0.8740533704387838), pvalue=np.float64(0.39075175029508025), df=np.int64(24))

In [15]:
t1c = 0

In [18]:
for _ in range(10000):
    samp = np.random.normal(loc = 5, scale = 2, size = 25)
    sm = sp.stats.ttest_1samp(samp, 5.0).pvalue
    if sm < 0.05:
        t1c += 1

In [19]:
t1c

522

In [27]:
t2c = 0
pc = 0

In [28]:
for _ in range(10000):
    samp = np.random.normal(loc = 5.5, scale = 2, size = 25)
    sm = sp.stats.ttest_1samp(samp, 5.0).pvalue
    if sm >= 0.05:
        t2c += 1
    if sm < 0.05:
        pc += 1

In [29]:
print(t2c/10000)
print(pc/10000)

0.7776
0.2224


In [32]:
samp = rng.integers(0, 10, size = 100)

In [33]:
samp

array([1, 8, 9, 3, 5, 9, 3, 9, 0, 8, 8, 4, 4, 5, 8, 9, 7, 4, 9, 9, 4, 9,
       9, 4, 3, 5, 0, 5, 2, 7, 2, 0, 5, 0, 0, 1, 8, 5, 2, 6, 7, 4, 6, 6,
       2, 0, 8, 2, 5, 0, 0, 5, 2, 5, 4, 1, 6, 9, 9, 8, 0, 8, 6, 4, 3, 1,
       4, 8, 9, 3, 9, 9, 2, 7, 2, 2, 7, 6, 0, 3, 5, 3, 6, 9, 9, 8, 1, 6,
       7, 8, 5, 9, 0, 3, 3, 9, 7, 8, 1, 4])

In [37]:
cntarr = np.zeros(10)
for i in range(len(samp)):
    cntarr[samp[i]] += 1

In [45]:
cntarr
cntarr.astype(int)

array([11,  6,  9,  9, 10, 11,  8,  7, 12, 17])

In [46]:
ecntarry = np.full(10, 10, dtype = int)

In [47]:
ecntarry

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [49]:
xsq = 0
for i in range(10):
    top = (cntarr[i] - ecntarry[i]) ** 2
    bot = ecntarry[i]
    xsq += top/bot

In [51]:
df = 9

In [53]:
sf = sp.stats.chi2.sf(xsq, df = 9)

In [54]:
print(sp.stats.chisquare(cntarr))
print(sf)
print(xsq)

Power_divergenceResult(statistic=np.float64(8.600000000000001), pvalue=np.float64(0.4749856866480098))
0.4749856866480098
8.600000000000001


In [55]:
na = np.random.normal(loc = 5.0, scale = 1.5, size = 20)
nb = np.random.normal(loc = 6.0, scale = 1.5, size = 20)

In [56]:
xahat = np.mean(na)
xbhat = np.mean(nb)

In [57]:
diffobs = np.abs(xahat - xbhat)

In [58]:
ec = 0

In [63]:
arr = np.concatenate((na, nb))

In [ ]:
for _ in range(10000):
    xar 