In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

In [3]:
np.random.seed(33550336)
rng = np.random.default_rng()

In [4]:
stuff = rng.random((5, 3))

In [5]:
stuff

array([[0.88244639, 0.92545162, 0.69464856],
       [0.70195323, 0.13607084, 0.71257308],
       [0.562789  , 0.40916349, 0.19785564],
       [0.60277147, 0.61575356, 0.95399814],
       [0.00141065, 0.16993716, 0.77204269]])

In [6]:
stuff[2, 0] = np.nan
stuff[1, 2] = np.nan
stuff[4, 1] = np.nan

In [7]:
stuff

array([[0.88244639, 0.92545162, 0.69464856],
       [0.70195323, 0.13607084,        nan],
       [       nan, 0.40916349, 0.19785564],
       [0.60277147, 0.61575356, 0.95399814],
       [0.00141065,        nan, 0.77204269]])

In [8]:
cm = np.sum(np.isnan(stuff), axis = 0)

In [9]:
cm

array([1, 1, 1])

In [10]:
cm/stuff.shape[0] * 100

array([20., 20., 20.])

In [11]:
meds = np.nanmedian(stuff, axis = 0)

In [12]:
stuff[2, 0] = meds[0]
stuff[1, 2] = meds[2]
stuff[4, 1] = meds[1]

In [13]:
stuff

array([[0.88244639, 0.92545162, 0.69464856],
       [0.70195323, 0.13607084, 0.73334562],
       [0.65236235, 0.40916349, 0.19785564],
       [0.60277147, 0.61575356, 0.95399814],
       [0.00141065, 0.51245852, 0.77204269]])

In [14]:
rad = 7
targ = 50
nm = rng.integers(low = targ - rad, high = targ + rad, size = 20, endpoint = True)

In [15]:
rn1 = rng.integers(0, 20)
rn2 = rng.integers(0, 20)

In [16]:
nm[rn1] = -100

In [17]:
nm[rn2] = 500

In [18]:
nm

array([  57,   55,   46,   48,   49,   43,   46,   50,   57,   44,   55,
         52,  500,   49,   53,   44,   53,   44, -100,   45])

In [19]:
q1 = np.percentile(nm, 25)
q3 = np.percentile(nm, 75)

In [20]:
iqr = q3 - q1

In [21]:
lowerb = q1 - 1.5 * iqr
upperb = q3 + 1.5 * iqr

In [22]:
np.clip(nm, lowerb, upperb)

array([57.   , 55.   , 46.   , 48.   , 49.   , 43.   , 46.   , 50.   ,
       57.   , 44.   , 55.   , 52.   , 66.625, 49.   , 53.   , 44.   ,
       53.   , 44.   , 31.625, 45.   ])

In [23]:
sm = np.array(['Low', 'Medium', 'High', 'Medium', 'Low', 'High'])
smnum = np.array([0, 1, 2, 1, 0, 2])

In [24]:
unord = np.array(['Red', 'Green', 'Blue', 'Red'])

In [25]:
sm = np.zeros((4,3))

In [26]:
sm[0, 0] = 1
sm[1, 1] = 1
sm[2, 2] = 1
sm[3, 0] = 1

In [27]:
sm

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [28]:
col1 = rng.integers(low =  20, high = 60, size = 5, endpoint = True)
col2 = rng.integers(low = 20000, high = 150000, size = 5, endpoint = True)

In [29]:
print(col1)
print(col2)

[53 58 29 49 58]
[ 90813 129421  96648  85036 147935]


In [30]:
newarray = np.column_stack((col1, col2))

In [31]:
newarray

array([[    53,  90813],
       [    58, 129421],
       [    29,  96648],
       [    49,  85036],
       [    58, 147935]])

In [32]:
mins = np.min(newarray, axis = 0)
maxs = np.max(newarray, axis = 0)

In [33]:
tmp = newarray.copy()
xnorm = (tmp - mins)/(maxs- mins)

In [34]:
mu = np.mean(newarray , axis = 0)
sig = np.std(newarray, axis = 0)

In [35]:
Z = (newarray - mu)/sig

In [36]:
Z

array([[ 0.33506136, -0.78395633],
       [ 0.80042435,  0.79593812],
       [-1.89868102, -0.5451798 ],
       [-0.03722904, -1.02035941],
       [ 0.80042435,  1.55355742]])

In [70]:
son = col1 ** 2

In [71]:
son2 = col1 * col2

In [72]:
son3 = np.column_stack((son, son2))

In [73]:
newthing = np.column_stack((newarray, son3))

In [74]:
newthing

array([[     53,   90813,    2809, 4813089],
       [     58,  129421,    3364, 7506418],
       [     29,   96648,     841, 2802792],
       [     49,   85036,    2401, 4166764],
       [     58,  147935,    3364, 8580230]])

In [75]:
ind = np.arange(5)
rng.shuffle(ind)

In [76]:
split = 4

In [77]:
tran = ind[:split]
tast = ind[split:]

In [95]:
xtr = newthing[tran]
xte = newthing[tast]
ztr = Z[tran]
zte = Z[tast]

In [96]:
xtr

array([[     58,  129421,    3364, 7506418],
       [     53,   90813,    2809, 4813089],
       [     58,  147935,    3364, 8580230],
       [     29,   96648,     841, 2802792]])

In [97]:
xte

array([[     49,   85036,    2401, 4166764]])

In [106]:
y = np.array([250, 180, 200, 310, 150])
ytr = y[tran]
yte = y[tast]
w = np.zeros(ztr.shape[1])
b = 0.0

In [107]:
yp = np.dot(ztr, w) + b

In [108]:
yp

array([0., 0., 0., 0.])

In [109]:
er = yp - ytr
l = np.mean(er ** 2)

In [110]:
dw = (2 / len(ytr)) * np.dot(ztr.T, er)
db = (2 / len(ytr)) * np.sum(er)

In [111]:
lr = 0.01

In [112]:
for i in range(5000):
    yp = np.dot(ztr, w) + b
    er = yp - ytr
    dw = (2 / len(ytr)) * np.dot(ztr.T, er)
    db = (2 / len(ytr)) * np.sum(er)
    w = w - lr * dw
    b = b - lr * db
    if i  % 500 == 0:
        print(yp)

[0. 0. 0. 0.]
[182.73605263 246.27157196 148.82048032 201.07046701]
[183.10907822 248.7503685  147.89254855 200.22483594]
[183.11699366 248.80347621 147.87253436 200.20649856]
[183.11716353 248.80461595 147.87210483 200.20610502]
[183.11716717 248.80464041 147.87209562 200.20609657]
[183.11716725 248.80464093 147.87209542 200.20609639]
[183.11716725 248.80464094 147.87209541 200.20609639]
[183.11716725 248.80464094 147.87209541 200.20609639]
[183.11716725 248.80464094 147.87209541 200.20609639]


In [117]:
yp

array([183.11716725, 248.80464094, 147.87209541, 200.20609639])

In [114]:
sm = np.dot(zte, w) + b

In [115]:
sm

array([253.55389575])

In [119]:
yte

array([310])